IDEMPIERE-5147  Improve Query.first() methods - performance
idempiere/idempiere pull request #1124
Opened 2022-01-10 14:46 UTC by igorpojzl

Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5147

Question: Do i need to move 
`String sql = buildSQL(null, true);`
in TRY block? 
buildSQL can throw IllegalStateException. Which can cause that pageSize is not set to original value.

2022-01-10 14:51 UTC, CarlosRuiz-globalqss commented
> Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5147
> 
> Question: Do i need to move `String sql = buildSQL(null, true);` in TRY block? buildSQL can throw IllegalStateException. Which can cause that pageSize is not set to original value.

Yes, please

2022-01-10 15:04 UTC, igorpojzl commented
Commited.

2022-01-11 14:29 UTC, CarlosRuiz-globalqss requested changes
Hi @igorpojzl

I tested this against oracle and the impact on the database is too high, because the poor implementation of the paging for oracle.

Can you please integrate the following patch:
[pr1124_PR.txt](https://github.com/idempiere/idempiere/files/7847290/pr1124_PR.txt)

I added changes to the oracle paging - and the same works perfect for postgresql.

Also added a unit test case for this paging, and it works fine.

2022-01-11 14:53 UTC, CarlosRuiz-globalqss commented on org.idempiere.test/src/org/idempiere/test/base/QueryTest.java
> +		System.setProperty("org.idempiere.db.debug", "true");
Sorry @igorpojzl  - can you please delete this line - I left that by mistake

2022-01-11 15:10 UTC, CarlosRuiz-globalqss approved these changes

2022-01-11 15:10 UTC, merged