IDEMPIERE-5014 Add stream interface to Query
idempiere/idempiere pull request #1298
Opened 2022-04-21 05:59 UTC by kriegfrj

https://idempiere.atlassian.net/jira/software/c/projects/IDEMPIERE/issues/IDEMPIERE-5014

Carlos requested a proof-of-concept - this is it.

2022-04-23 05:43 UTC, hengsin requested changes
looks good, just need to add missing javadoc and update the existing one to reflect the changes make.

2022-04-28 07:29 UTC, kriegfrj commented
Made changes to the Javadoc as requested and also added test cases thanks to @hengsin 's pointer as to where to put them.

Also added the AssertJ dependency which I made use of in my tests.

2022-04-28 11:36 UTC, hengsin commented
hi @kriegfrj ,

The added dependency is fine but you need to add the location to "maven.locations.xml", and update the timestamp (yymmdd) based target name inside "org.idempiere.p2.targetplatform.target"  and "org.idempiere.p2.targetplatform.tpd" ( for e.g to idempiere-220428 ).

Regards,
Low

2022-04-28 13:46 UTC, kriegfrj commented
> hi @kriegfrj ,
> 
> The added dependency is fine but you need to add the location to "maven.locations.xml", and update the timestamp (yymmdd) based target name inside "org.idempiere.p2.targetplatform.target" and "org.idempiere.p2.targetplatform.tpd" ( for e.g to idempiere-220428 ).
> 
> Regards, Low

Thanks @hengsin , done, done and done.

I take it that `org.idempiere.p2.targetplatform.target` is in some way derived from the other two files - are there any instructions on how to generate it? Thanks!

2022-04-28 14:06 UTC, hengsin commented
[- install plugin from https://github.com/eclipse-cbi/targetplatform-dsl
org.idempiere.p2.targetplatform.target is generated from org.idempiere.p2.targetplatform.tpd using Eclipse plugin from  . the maven.locations.xml content](https://wiki.idempiere.org/en/Building_iDempiere_by_tycho#update_.5Bidempiere-source.5D.2Forg.idempiere.p2.targetplatform.2Forg.idempiere.p2.targetplatform.target)

2022-04-29 02:27 UTC, hengsin approved these changes
looks good

2022-04-29 02:27 UTC, merged