IDEMPIERE-5356 - Add Printing Support to ProcessInfoDialog
idempiere/idempiere pull request #1412
Opened 2022-07-26 12:52 UTC by PeterTakacs300

JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5356

2022-07-26 12:56 UTC, PeterTakacs300 commented
Hi @hengsin , I'm not sure how you ment _"printing should depends solely on whether the linked document is printable"_. For now, we tried similar approach as in ReportCtl.start method.

2022-07-26 13:08 UTC, hengsin commented
I means whether the linked document is with a document Report Engine Type. In other words, instead of hard coding the process info id, you check whether the ad_table_id of the process log record is associated with a document Report Engine Type (Shipment, Invoice, Order, etc). Another alternative is to add a report engine type field to the process log and use that to decide whether printing is available.

2022-07-31 12:56 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +					reportEngineType = ReportEngine.getReportEngineType(tableID);
should check reportEngineType is valie (i.e not -1) here.

2022-07-31 12:58 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +			pdfList.add(re.getPDF());
This code block only work if all m_logs record is of same ad_table_id and with record_id > 0. I don't think it is a good idea to assume that's always the case.

2022-07-31 12:59 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +	private static final CLogger log = CLogger.getCLogger(WGenForm.class);
WGenForm.class is wrong here.

2022-07-31 13:00 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +			Clients.showBusy("Processing...");
not translated.

2022-07-31 13:01 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +				File outFile = File.createTempFile(printTmpFileName, ".pdf");
printTmpFileName is not being set any where ...

2022-07-31 13:02 UTC, hengsin commented on org.adempiere.base/src/org/compiere/print/ReportEngine.java
> +	public static int[] getDocTableIDs() {
this public method is not needed

2022-07-31 13:06 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +					reportEngineType = ReportEngine.getReportEngineType(tableID);
this loop of ReportEngine.getDocTableIDs() is not good, it should be simplify to just `if (ReportEngine.getReportEngineType(tableID) >= 0) return true;`

2022-08-01 08:50 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +				re = ReportEngine.get (Env.getCtx(), ReportEngine.getReportEngineType(m_logs[i].getAD_Table_ID()), recordID);
the safe thing to do here is `int reportEngineType = ReportEngine.getReportEngineType(m_logs[i].getAD_Table_ID()); if (reportEngineType >= 0) { ...}`

2022-08-02 03:05 UTC, hengsin requested changes

2022-08-02 03:05 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +				log.log(Level.SEVERE, e.getLocalizedMessage(), e);
Better just rethrow as runtime exception instead. Otherwise it is silent error to user.

2022-08-02 03:05 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +				log.log(Level.SEVERE, e.getLocalizedMessage(), e);
Better just rethrow as runtime exception instead. Otherwise it is silent error to user.

2022-08-02 03:05 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +			Clients.response(new AuEcho(ProcessInfoDialog.this, "onPrint", null));
the alternative is to use `Executions.schedule(this.getDesktop(), e -> onPrint(), new Event("onPrint"));`. The benefit is you can declare onPrint as private and didn't add a "fake" public method to ProcessInfoDialog (fake as in although it is public but it is not means to be call directly by other class).

2022-08-02 06:37 UTC, hengsin requested changes

2022-08-02 06:37 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +				throw new RuntimeException(e.getLocalizedMessage());
best practise is to use throw new RuntimeException(e.getLocalizedMessage(), e); instead so the exception stack trace is not lost. same goes for the throw below.

2022-08-02 06:37 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +				Clients.clearBusy();
this should goes before "try{", same as the Clients.clearBusy() call below.

2022-08-02 07:31 UTC, hengsin requested changes

2022-08-02 07:31 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +		// Loop through all items
hmm ... sorry for the mistake in previous review, Clients.clearBusy(); should be the first line in this method, not the 2 place below. No matter what happens below, we need to make sure the busy mask is clear.

2022-08-02 07:31 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/ProcessInfoDialog.java
> +	 * @return
this is minor but @return is empty here.

2022-08-02 09:10 UTC, merged