IDEMPIERE-5362 - Attribute Dialog should use scroll when many attributes
idempiere/idempiere pull request #1418
Opened 2022-08-02 09:05 UTC by PeterTakacs300

JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5362

2022-08-02 09:13 UTC, PeterTakacs300 commented
Before:
![Screenshot 2022-08-02 at 10 59 17](https://user-images.githubusercontent.com/93127072/182337240-40554bcf-a755-474d-b5db-e95d99ece4c8.png)

After:
![Screenshot 2022-08-02 at 10 54 58](https://user-images.githubusercontent.com/93127072/182337334-dae92e1b-1be5-4dcd-92a5-58dc6b977c66.png)

Problem:
![Screenshot 2022-08-02 at 10 55 51](https://user-images.githubusercontent.com/93127072/182337402-3e65be8a-6774-4172-947c-a9cafa10071b.png)

I temporarily hardcoded the height to 500px, I would need help with setting max-height to the dialog, so there would not be the empty space seen on the picture above, when we have less attributes.

2022-08-03 03:09 UTC, hengsin commented
hi @PeterTakacs300 , you have to use css or setstyle to set min or max height (https://www.w3schools.com/cssref/pr_dim_min-height.asp)

2022-08-03 07:03 UTC, PeterTakacs300 commented
Current state

Max height:
![Screenshot 2022-08-03 at 08 59 49](https://user-images.githubusercontent.com/93127072/182544782-03bdab23-23e5-4c20-8b9c-ebfe0f3a006e.png)

Shrinking when there are less attributes:
![Screenshot 2022-08-03 at 09 00 09](https://user-images.githubusercontent.com/93127072/182545037-04bb1298-1339-40be-96c2-b4e7da7b2454.png)

2022-08-04 07:11 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/window/WPAttributeDialog.java
> +		mainLayout.setStyle("max-height: 600px;");
This wouldn't works well on mobile with smaller height. one option is to do it with condition, i.e `if (ClientInfo.maxHeight(600) mainLayout.setStyle("max-height: 100%;"); else mainLayout.setStyle("max-height: 600px;");`

As a safety net, we can setMaxizable(true) for the dialog. This give user a way to make the dialog usable if there's problem with default sizing set by the application.

2022-08-04 07:28 UTC, PeterTakacs300 commented
https://user-images.githubusercontent.com/93127072/182789155-f007b4b9-f3d2-4dde-bbaf-0dc38f34b73b.mp4

2022-08-04 10:07 UTC, hengsin requested changes
please update ticket with the details of other changes.

2022-08-04 10:44 UTC, norbertbede commented
done

2022-08-04 11:31 UTC, CarlosRuiz-globalqss requested changes
Please check comments in ticket

2022-08-08 17:03 UTC, CarlosRuiz-globalqss approved these changes

2022-08-08 17:04 UTC, CarlosRuiz-globalqss commented
Tested, I find this OK.  @hengsin  ?

2022-08-09 07:07 UTC, hengsin commented
ok for me.

2022-08-09 07:07 UTC, hengsin approved these changes
tested

2022-08-09 07:08 UTC, merged