IDEMPIERE-5339   GL AP/AR and RLL/RLG facts posted on wrong side in allocation reversal document using Payment Reverse-Accrual
idempiere/idempiere pull request #1420
Opened 2022-08-02 11:56 UTC by etantg

https://idempiere.atlassian.net/browse/IDEMPIERE-5339

Test Case: 
May-22 Customer Invoice AUD 1000, Rate AUD/EUR 0.7, AUD/USD 0.8
June-22 Payment AUD 1000,   Rate AUD/EUR 0.8, AUD/USD 0.9
July-22 Payment Reversal, same rate as June-22 for simplicity

GL posting:
Invoice:
Dr. AR AUD=1000, EUR=700, USD=800
Cr. Revenue EUR=700, USD=800
not VAT for simplicity

Payment/Receipt:
Dr. Bank/Cash AUD=1000, EUR=800, USD=900
Cr. Unallocated Cash AUD=1000, EUR=800, USD=900

Payment Allocation:
Dr. Unallocated Cash AUD=1000, EUR=800, USD=900
Cr. AR AUD=1000, EUR=800, USD=900
Cr. Realized gain EUR=100, USD=100
Dr. AR EUR=100, USD=100

Payment Allocation Reversal using Reverse-Accrual:
Cr. Unallocated Cash AUD=1000, EUR=800, USD=900
Dr. AR AUD=1000, EUR=800, USD=900
Dr. Realized gain EUR=100, USD=100
Cr. AR EUR=100, USD=100

2022-08-02 12:02 UTC, hengsin requested changes

2022-08-02 12:02 UTC, hengsin commented on org.idempiere.test/src/org/idempiere/test/model/Allocation2ndAcctSchemaTest.java
> +			rollback();
please move rollback() above deleteConversionRate(cr1a), this will give problem with Oracle.

2022-08-02 12:02 UTC, hengsin commented on org.idempiere.test/src/org/idempiere/test/model/Allocation2ndAcctSchemaTest.java
> +			rollback();
please move rollback() above deleteConversionRate(cr1a), this will give problem with Oracle.

2022-08-02 12:07 UTC, hengsin commented on org.adempiere.base/src/org/compiere/acct/Doc_AllocationHdr.java
> +						|| (!invoice.isSOTrx() && invoice.getGrandTotal().signum() < 0 && !invoice.isCreditMemo()))
it seem this if condition block is repeated multiple times here, would be good if we can extract that out as a method instead to reduce duplicate code.

2022-08-03 08:20 UTC, etantg commented
Hi @hengsin, I've made the changes. Please review.

2022-08-04 08:52 UTC, hengsin approved these changes
Pass unit test and tested by Michael Powacht

2022-08-04 08:52 UTC, merged