IDEMPIERE-5405 - Drill Assistant - potential Cross Tenant Issue on Table tab
idempiere/idempiere pull request #1461
Opened 2022-09-05 06:22 UTC by PeterTakacs300

JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5405

2022-09-17 11:10 UTC, CarlosRuiz-globalqss requested changes

2022-09-17 11:10 UTC, CarlosRuiz-globalqss commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/WDrillReport.java
> +		Integer printFormatID = new Query(Env.getCtx(), MPrintFormat.Table_Name, " AD_Table_ID = ? AND AD_Client_ID = ? ", null).setParameters(drillTable.getKey(), Env.getAD_Client_ID(Env.getCtx())).firstI
would be simpler to use the .setClient_ID() of Query

But, I'm wondering if print formats from System tenant must be included too?
If that's the case then the query must be " AND AD_Client_ID IN (0,?) "

2022-09-17 11:13 UTC, CarlosRuiz-globalqss commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/WDrillReport.java
> +		Integer printFormatID = new Query(Env.getCtx(), MPrintFormat.Table_Name, " AD_Table_ID = ? AND AD_Client_ID = ? ", null).setParameters(drillTable.getKey(), Env.getAD_Client_ID(Env.getCtx())).firstI
Something additional here, usually when getting a first record you must add an ORDER BY clause.

In this case we also probably would like to put first the default print format, so maybe an ORDER BY like:

IsDefault DESC, Created DESC

2022-09-27 06:47 UTC, norbertbede commented
hi @CarlosRuiz-globalqss can we close this please ?

2022-10-11 11:10 UTC, CarlosRuiz-globalqss approved these changes

2022-10-11 11:10 UTC, merged