IDEMPIERE-5418 - Add Translation for AD_ChartDatasource
idempiere/idempiere pull request #1479
Opened 2022-09-13 07:56 UTC by PeterTakacs300

JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5418

2022-10-06 06:39 UTC, hengsin commented
Hi @PeterTakacs300 , please document the new feature in wiki.

2022-10-11 16:03 UTC, norbertbede commented
@hengsin i can create documentation, however this looks me not new features, simple improvement _trl option.
if you don't agree i will do it.

2022-10-13 10:21 UTC, CarlosRuiz-globalqss requested changes

2022-10-13 10:21 UTC, CarlosRuiz-globalqss commented on migration/iD10/oracle/202209121558_IDEMPIERE-5418.sql
> +INSERT INTO AD_Column (AD_Column_ID,Version,Name,AD_Table_ID,ColumnName,FieldLength,IsKey,IsParent,IsMandatory,IsTranslated,IsIdentifier,SeqNo,IsEncrypted,AD_Reference_ID,AD_Client_ID,AD_Org_ID,IsAct
The configuration on translation tables is to define the constraints cascade, to be deleted automatically when the parent record is deleted.

2022-10-13 10:21 UTC, CarlosRuiz-globalqss commented on migration/iD10/oracle/202209121558_IDEMPIERE-5418.sql
> +ALTER TABLE AD_ChartDatasource_Trl ADD CONSTRAINT ADChartDatasource_ADChartDatas FOREIGN KEY (AD_ChartDatasource_ID) REFERENCES ad_chartdatasource(ad_chartdatasource_id) DEFERRABLE INITIALLY DEFERRED
changing the FK to cascade must change this statement too - both in oracle and postgresql

2022-10-13 11:35 UTC, CarlosRuiz-globalqss commented
@PeterTakacs300 - I noticed the scripts are doing nothing to translate the current charts.

The attached patch here:
[IDEMPIERE-5418_pr1.txt](https://github.com/idempiere/idempiere/files/9776134/IDEMPIERE-5418_pr1.txt)

Implements the translation on all translatable elements in the "Sales Rep Dashboard"
It additionally fixes the problem with the cascade foreign key requested above.


@hengsin - can you please take a look to the patch too?
It's related to the billboard implementation, I didn't find a way to translate the month names in the "Sales YTD" chart, so I changed the format from "Aug 2022" to "2022-08" - is that acceptable?  Or is there a way to show the names in the language the user is logged in?

2022-10-13 11:51 UTC, hengsin commented
hi @CarlosRuiz-globalqss , since I'm not actually using billboard in production, it is more whether that's acceptable to @norbertbede  and perhaps @nmicoud. anyway, I will check whether that's translatable to the login locale.

2022-10-13 11:54 UTC, nmicoud commented
hi,
I'm still using the "old" charts so never tried billboard ; I think 2022-08 is fine.
And we can check later if that can be translated according to locale, if a customer starts to complain?

2022-10-13 11:55 UTC, norbertbede commented
the scope of this PR was only extend chart source by translation. not fix in billboard. Later we can make a PR for billboard fixes. Billboard  js changes are very experimental, so we don't want to create many issues, but a complex one.

2022-10-13 11:58 UTC, CarlosRuiz-globalqss commented
> the scope of this PR was only extend chart source by translation. not fix in billboard.

Yes, that's precisely why I reviewed this, it doesn't make sense to add a translatable table if is not used anywhere, and then I noticed that all the translations in charts were not used (not just on billboard, but I think they are not being used also in the jfreechart version, but I didn't try to fix that one).

> Later we can make a PR for billboard fixes. Billboard js changes are very experimental, so we don't want to create many issues, but a complex one.

I already added the patch for @PeterTakacs300 to integrate.

2022-10-13 12:54 UTC, CarlosRuiz-globalqss approved these changes

2022-10-13 12:59 UTC, hengsin commented
hi @CarlosRuiz-globalqss , go ahead to merge this if doc is not necessary.

2022-10-13 13:12 UTC, merged