IDEMPIERE-5458 - Timezone defined by Organization
idempiere/idempiere pull request #1568
Opened 2022-11-17 19:29 UTC by matheus-marcelinux

https://idempiere.atlassian.net/browse/IDEMPIERE-5458

# Pull Request Checklist

## Checklist:

- [ ] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [ ] My code follows the best practices of this project
- [ ] I have performed a self-review of my own code
- [ ] My code is easy to understand and review. 
- [ ] In hard-to-understand areas, I have commented my code.
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2022-11-21 14:38 UTC, matheus-marcelinux commented on migration/iD10/oracle/202211011331_IDEMPIERE-5458.sql
> +UPDATE AD_SysConfig SET Value='muriloht',Updated=TO_TIMESTAMP('2022-11-01 13:31:02','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_SysConfig_ID=50001
Hi @CarlosRuiz-globalqss , done , can you send a new one ? Thanks !

2022-11-24 06:11 UTC, hengsin requested changes

2022-12-07 01:26 UTC, hengsin commented on migration/iD10/oracle/202211011331_IDEMPIERE-5458.sql
> +ALTER TABLE AD_OrgInfo MODIFY AD_Client_ID NUMBER(10)
hi @matheus-marcelinux , any update ?

2022-12-07 14:13 UTC, matheus-marcelinux commented on migration/iD10/oracle/202211011331_IDEMPIERE-5458.sql
> +ALTER TABLE AD_OrgInfo MODIFY AD_Client_ID NUMBER(10)
hi @hengsin, sorry for the late, done

2022-12-20 02:43 UTC, matheus-marcelinux commented
> Missing migration script to add Time Zone field to Organization Info Tab.

Sorry @hengsin i was working on other stuff last weeks and forgot that. I'll create the missing script tomorrow

2023-01-25 01:37 UTC, hengsin requested changes
hi @matheus-marcelinux , please resolve the merge conflict.

@CarlosRuiz-globalqss , should the migration script for this goes into iD10 or 11 ?

2023-01-25 12:12 UTC, CarlosRuiz-globalqss commented
> @CarlosRuiz-globalqss , should the migration script for this goes into iD10 or 11 ?

Yes, better to move to iD11.

Documentation is also pending

2023-01-30 16:49 UTC, matheus-marcelinux commented
hi @CarlosRuiz-globalqss @hengsin i'll do that

2023-02-01 03:42 UTC, hengsin approved these changes
tested

2023-02-01 03:43 UTC, merged