# IDEMPIERE-5488 - adding missing ids in .tdp file and regenerating .…
idempiere/idempiere pull request #1583
Opened 2022-11-26 14:16 UTC by matheus-marcelinux

…target

https://idempiere.atlassian.net/browse/IDEMPIERE-5488

# Pull Request Checklist

## Checklist:

- [ ] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [ ] My code follows the best practices of this project
- [ ] I have performed a self-review of my own code
- [ ] My code is easy to understand and review. 
- [ ] In hard-to-understand areas, I have commented my code.
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2022-11-27 06:11 UTC, hengsin commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd
> +location binary-file-zk "https://idempiere.github.io/binary.file/p2.zk/9.6.2" {
please simplify to zk

2022-11-27 06:12 UTC, hengsin requested changes

2022-11-27 06:12 UTC, hengsin commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd
> +location binary-file-repackaged "https://idempiere.github.io/binary.file/p2.repackaged/9.0.0" {
please simplify to repackaged

2022-11-27 06:12 UTC, hengsin commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd
> +location eclipse-2021-06 "https://download.eclipse.org/eclipse/updates/4.20" {
please simplify to eclipse

2022-11-27 06:12 UTC, hengsin commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd
> +location jasperstudio-updatesite "https://sourceforge.net/projects/jasperstudio/files/updatesite/6.17.0" {
please simplify to jasperstudio

2022-11-27 17:11 UTC, matheus-marcelinux commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd
> +location eclipse-2021-06 "https://download.eclipse.org/eclipse/updates/4.20" {
done

2022-11-27 17:11 UTC, matheus-marcelinux commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd
> +location binary-file-repackaged "https://idempiere.github.io/binary.file/p2.repackaged/9.0.0" {
done

2022-11-27 17:11 UTC, matheus-marcelinux commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.tpd
> +location binary-file-zk "https://idempiere.github.io/binary.file/p2.zk/9.6.2" {
done

2022-11-29 02:41 UTC, hengsin approved these changes
trivial fix, good to go

2022-11-29 02:41 UTC, merged