IDEMPIERE-5611 Record ID Editor doesn't work with House Keeping
idempiere/idempiere pull request #1720
Opened 2023-03-10 19:11 UTC by CarlosRuiz-globalqss

- Fix zoom window on tables that have this field empty and have a window associated

https://idempiere.atlassian.net/browse/IDEMPIERE-5611

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [x] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works

2023-03-12 03:52 UTC, hengsin commented
[pr1720.patch.txt](https://github.com/idempiere/idempiere/files/10949940/pr1720.patch.txt)
- Fix zoom and lookup without AD_Window_ID update

2023-03-13 11:45 UTC, hengsin requested changes
please review attached patch, thanks.

2023-03-13 14:13 UTC, CarlosRuiz-globalqss commented
> please review attached patch, thanks.

Thanks @hengsin - added your commit with a minor fix to also discover for TabLevel > 0

I think still the migration script is useful, after the patch the RecordID works, but the Zoom doesn't.

2023-03-14 11:09 UTC, hengsin commented
I didn't means to remove the migration script but the lookup it is something that should be fixed as well. will check whether I can fix the zoom issue too.

2023-03-15 14:00 UTC, CarlosRuiz-globalqss commented
> [pr1720.zoom.patch.txt](https://github.com/idempiere/idempiere/files/10969836/pr1720.zoom.patch.txt)
> 
>     * Fix zoom when AD_Table.AD_Window_ID is null.

Thanks @hengsin - it worked fine, integrated and used it too in InfoGeneralPanel

2023-03-15 14:01 UTC, hengsin commented on migration/iD10/postgresql/202303081200_IDEMPIERE-5611.sql
> +
hi @CarlosRuiz-globalqss , is there a risk here that this will update customization of existing implementations ?

2023-03-15 14:34 UTC, hengsin approved these changes
tested

2023-03-15 14:34 UTC, merged