IDEMPIERE-5666 - Prevent Closing the Tab of a Running Report
idempiere/idempiere pull request #1778
Opened 2023-04-12 10:43 UTC by PeterTakacs300

JIRA ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-5666

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2023-04-13 14:31 UTC, hengsin requested changes

2023-04-13 14:31 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java
> +			if (parentTab != null && (parentTab.getClass().equals(Tabpanel.class) || parentTab.getClass().equals(DesktopTabpanel.class))) {
better to use instanceof instead.

2023-04-13 14:31 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java
> +	private boolean running = false;
this is not needed

2023-04-13 14:31 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessDialog.java
> +		if(!running) {
replace !running with !isUILocked()

2023-04-13 14:31 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessModalDialog.java
>  }	//	ProcessModalDialog
Should use a mechanism similar to ProcessDialog instead of this ZkReportViewer only approach.

2023-04-14 07:22 UTC, hengsin commented
[pr1778.patch1.txt](https://github.com/idempiere/idempiere/files/11230028/pr1778.patch1.txt)

2023-04-14 07:22 UTC, hengsin requested changes
please review attached patch, thanks.

2023-04-14 07:48 UTC, PeterTakacs300 commented
patch reviewed, applied

2023-04-14 08:06 UTC, hengsin approved these changes
tested

2023-04-14 08:06 UTC, merged