validation when run process and input min max value on process parameter
idempiere/idempiere pull request #1908
Opened 2023-06-24 09:00 UTC by uthadehikaru

- added validation for min and max value when run process
- added validation when insert min and max value format

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [ ] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [x] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2023-06-29 11:16 UTC, CarlosRuiz-globalqss requested changes
tested succesfully with numbers, dates and strings

2023-06-29 11:16 UTC, CarlosRuiz-globalqss commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/ProcessParameterPanel.java
> +						Dialog.error(m_WindowNo, field.getColumnName()+" MoreThanMaxValue", field.getValueMax());
MoreThanMaxValue and LessThanMinValue are translatable messages, you must parse correctly the message for the dialog

2023-06-29 11:16 UTC, CarlosRuiz-globalqss commented on org.adempiere.base/src/org/compiere/model/MProcessPara.java
> +				if(getAD_Reference_ID()==15) { // Date
please use here DisplayType.Date instead of the hardcoded 15, same below for the other references.

2023-07-02 12:03 UTC, uthadehikaru commented
update pull request as requested

2023-07-03 10:52 UTC, CarlosRuiz-globalqss requested changes
Hi @uthadehikaru 

I did a refactoring of the code, can you please apply the following patch to the pull request?
[PR1908pr.patch.txt](https://github.com/idempiere/idempiere/files/11936021/PR1908pr.patch.txt)

Regards,

Carlos Ruiz

2023-07-03 15:13 UTC, CarlosRuiz-globalqss approved these changes
tested

2023-07-03 15:14 UTC, merged