IDEMPIERE-4697 : temporary filename "adempiere_"
idempiere/idempiere pull request #2000
Opened 2023-09-12 08:41 UTC by uthadehikaru

https://idempiere.atlassian.net/browse/IDEMPIERE-4697

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [ ] In hard-to-understand areas, I have commented my code.
- [ ] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2023-09-14 12:20 UTC, CarlosRuiz-globalqss requested changes
Hi @uthadehikaru 

Peer review:

* the name of the SysConfig must be more verbose about its purpose, I would suggest something like UPLOAD_TEMP_FILENAME_PREFIX
* the SysConfig name must be added to the class MSysConfig as a constant and referenced in WFilenameEditor
* the SysConfig must be configurable per tenant
* as the SysConfig is configurable per tenant is better to create a migration script to insert it (please fill properly the description)
* please also add documentation at [the wiki](https://wiki.idempiere.org/en/System_Configurator_(Window_ID-50006))

2023-09-17 05:30 UTC, uthadehikaru commented
i will added documentation after this pull request is merged

2023-09-18 10:29 UTC, CarlosRuiz-globalqss requested changes
Hi @uthadehikaru 

Can you please apply the following patch:
[pr2000PR.patch.txt](https://github.com/idempiere/idempiere/files/12646808/pr2000PR.patch.txt)

The MSysConfig call still requires a default in case somebody decides to inactivate it.

I also changed the default to idempiere instead of adempiere

2023-09-18 12:44 UTC, CarlosRuiz-globalqss approved these changes

2023-09-18 12:44 UTC, merged