IDEMPIERE-3989 - fast entity type identification
idempiere/idempiere pull request #2048
Opened 2023-10-06 14:21 UTC by VitorHenri

# Pull Request Checklist

- [ ] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [ ] My code follows the best practices of this project
- [ ] I have performed a self-review of my own code
- [ ] My code is easy to understand and review. 
- [ ] I have checked my code and corrected any misspellings
- [ ] In hard-to-understand areas, I have commented my code.
- [ ] My changes generate no new warnings
### Tests
- [ ] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2023-10-12 07:31 UTC, hengsin requested changes
Entity type for tab is shown in te "How To"  box, but entity type for field is not shown in "Tool Tip" box, looks incomplete.

2023-10-12 07:31 UTC, hengsin commented on .project
> +</projectDescription>
please remove this from change set.

2023-10-12 07:31 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/HelpWindow.java
> +				eType = eType.replace("**U**","");
Why the indicator for user define customization is not shown to user ?

2023-10-13 13:38 UTC, VitorHenri commented
Hello @hengsin , I made some adjustments about what you mentioned, displaying the field's entity type in Tool Tip, and adjusting it to show the user definition if any.

2023-10-15 03:00 UTC, hengsin requested changes

2023-10-16 08:46 UTC, CarlosRuiz-globalqss requested changes

2023-10-16 11:50 UTC, VitorHenri commented on org.adempiere.base/src/org/compiere/model/MSysConfig.java
> +    public static final String ZK_DISPLAY_ENTITYTYPE_INFORMATION = "ZK_DISPLAY_ENTITYTYPE_INFORMATION";
Done!

2023-10-16 11:50 UTC, VitorHenri commented on migration/iD11/postgresql/202310061103_IDEMPIERE-3989.sql
> +CREATE OR REPLACE VIEW AD_Window_vt(AD_Language, AD_Window_ID, Name, Description, Help, WindowType, AD_Color_ID, AD_Image_ID, IsActive, WinWidth, WinHeight, IsSOTrx, AD_Window_UU, entitytype) AS SELE
Hi @CarlosRuiz-globalqss, I didn't find a view called AD_Window_V, just AD_Window_VT

2023-10-16 12:26 UTC, CarlosRuiz-globalqss commented on migration/iD11/postgresql/202310061103_IDEMPIERE-3989.sql
> +CREATE OR REPLACE VIEW AD_Window_vt(AD_Language, AD_Window_ID, Name, Description, Help, WindowType, AD_Color_ID, AD_Image_ID, IsActive, WinWidth, WinHeight, IsSOTrx, AD_Window_UU, entitytype) AS SELE
Seems like the view AD_Window_VT is not used at all, no need to add entity type in such case for that view.  Indeed that could be a candidate for deletion.

WDYT @hengsin ?

2023-10-16 12:29 UTC, CarlosRuiz-globalqss commented
@VitorHenri - please check the checklist of the Description of the pull request and mark the things that you reviewed.

Can you also please take a look to my comment at https://idempiere.atlassian.net/browse/IDEMPIERE-3989?focusedCommentId=50105

2023-11-10 15:27 UTC, CarlosRuiz-globalqss requested changes
Please also create NF11 documentation.

I noticed the following points where there are changes:
* Help pages
* Tooltip and How To in the right panel
* Field right click context > Change Log

2023-11-10 15:27 UTC, CarlosRuiz-globalqss commented on org.adempiere.ui.zk/WEB-INF/src/web/theme/default/css/fragment/desktop.css.dsp
> +.help-entitytype {
when changing theme please change also the timestamp on file org.adempiere.ui.zk/WEB-INF/src/metainfo/zk/lang-addon.xml
as explained at https://wiki.idempiere.org/en/Check_List_Peer_Review#Code_Peer_Review

2023-11-10 15:27 UTC, CarlosRuiz-globalqss commented on migration/iD11/oracle/202310061103_IDEMPIERE-3989.sql
> +INSERT INTO AD_ViewColumn (AD_Client_ID,AD_Org_ID,AD_ViewColumn_ID,AD_ViewColumn_UU,Created,CreatedBy,EntityType,IsActive,Updated,UpdatedBy,AD_ViewComponent_ID,ColumnName,ColumnSQL,SeqNo) VALUES (0,0
the entity type of the 5 new records on AD_ViewColumn are wrong, must be 'D' instead of 'U'

2023-11-10 15:27 UTC, CarlosRuiz-globalqss commented on migration/iD11/oracle/202310061103_IDEMPIERE-3989.sql
> +CREATE OR REPLACE VIEW AD_Field_vt(AD_Language, AD_Window_ID, AD_Tab_ID, AD_Field_ID, AD_Table_ID, AD_Column_ID, Name, Description, Help, IsDisplayed, DisplayLogic, DisplayLength, SeqNo, SortNo, IsSa
Oracle sqlplus doesn't support lines with more than 2.500 characters:
this will cause SP2-0027

Please split this line.

2023-11-29 12:54 UTC, VitorHenri commented
Applied adjustments

2024-01-09 13:46 UTC, CarlosRuiz-globalqss commented
Hi @VitorHenri - please move the migration scripts to folder iD12

2024-01-09 13:59 UTC, VitorHenri commented
Scripts moved to iD12 folder

2024-01-18 06:32 UTC, hengsin commented
hi @CarlosRuiz-globalqss , is this ready for merge ?

2024-01-18 12:01 UTC, CarlosRuiz-globalqss requested changes
@VitorHenri 

please apply the following patch:

[pr2048PR.patch.txt](https://github.com/idempiere/idempiere/files/13976218/pr2048PR.patch.txt)

2024-01-18 12:52 UTC, CarlosRuiz-globalqss commented
> hi @CarlosRuiz-globalqss , is this ready for merge ?

not yet - I asked to apply another patch - found that the migration scripts were generated not using centralized IDs

2024-01-18 16:22 UTC, VitorHenri commented
Hi @hengsin, maybe I'm doing something wrong, but it looks like the scripts in this patch are the same as those already committed.

2024-01-18 16:36 UTC, CarlosRuiz-globalqss commented
> Hi @CarlosRuiz-globalqss , maybe I'm doing something wrong, but it looks like the scripts in this patch are the same as those already committed.

You're right - I uploaded the wrong patch, please apply this one:
[pr2048PR_2.patch.txt](https://github.com/idempiere/idempiere/files/13979330/pr2048PR_2.patch.txt)

2024-01-18 18:19 UTC, CarlosRuiz-globalqss commented
Thanks @VitorHenri - I forgot to fix also the oracle script, that goes with this fix:

[pr2048PR_3.patch.txt](https://github.com/idempiere/idempiere/files/13980414/pr2048PR_3.patch.txt)

2024-01-22 16:09 UTC, CarlosRuiz-globalqss commented
Hi @VitorHenri - I didn't notice there were nextid() also in the other migration script.

Please add the following patch:
[pr2048PR_4.patch.txt](https://github.com/idempiere/idempiere/files/14012663/pr2048PR_4.patch.txt)

This time I did also code peer review and tests

- most of the fixes are removing initial spaces and adding spaces within parameters to follow the same convention of the rest of the lines, and generate serialVersionUID when required

2024-01-22 16:17 UTC, VitorHenri commented
Hi @CarlosRuiz-globalqss, thanks! Patch applied.

2024-01-22 16:47 UTC, CarlosRuiz-globalqss approved these changes
Hi @hengsin - I tested this successfully

Are you OK with the changes?

I see there are some public methods that were changed to add EntityType as a parameter, but not adding a new method - probably not a big deal as most of those methods must be intended for internal core use.

But I better leave it to your advice if push this, or request some additional changes.

2024-01-23 03:11 UTC, hengsin requested changes

2024-01-23 03:11 UTC, hengsin commented on org.adempiere.base/src/org/compiere/util/Env.java
> +	public static boolean IsShowTechnicalInfOnHelp(Properties ctx)
Please remove the ctx parameter, not needed.

2024-01-23 03:11 UTC, hengsin commented on org.adempiere.base/src/org/compiere/model/I_AD_UserPreference.java
> +    public static final String COLUMNNAME_IsShowTechnicalInfOnHelp = "IsShowTechnicalInfOnHelp";
this is just for entity type ? perhaps should just use "IsShowEntityType" instead ?

2024-01-23 03:11 UTC, hengsin commented on org.adempiere.base/src/org/compiere/util/Env.java
> +	public static boolean IsShowTechnicalInfOnHelp(Properties ctx)
this is just for entity type ? perhaps should just use "IsShowEntityType" instead ?

2024-01-23 03:11 UTC, hengsin commented on org.adempiere.base/src/org/compiere/model/GridTab.java
> +		if (getField("EntityType") != null && Env.getCtx().getProperty("EntityType") != null) {
"Env.getCtx().getProperty("EntityType")" - where is this set ?

2024-01-31 04:09 UTC, hengsin approved these changes
looks good

2024-01-31 04:09 UTC, merged