IDEMPIERE-5980:spring-jcl make conflict between an export and import (slow down start idempiere on some condition)
idempiere/idempiere pull request #2175
Opened 2024-01-03 03:38 UTC by hieplq

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [ ] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2024-01-03 10:10 UTC, hengsin commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target
> +      <repository id="jasperstudio" location="https://p2.thanhhoawood.vn/p2.jasper/6.17.0"/>
non-standard location ...

2024-01-03 10:11 UTC, hengsin commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target
> +Import-Package:        org.apache.commons.logging;version="[1.1.1,2)";resolution:=optional,org.apache.commons.logging.impl;version="[1.1.1,2)";resolution:=optional,org.apache.tools.ant;version="[1.7,
isn't the commons logging version in current target platform 1.2 instead of 1.1.x ?

2024-01-03 10:11 UTC, hengsin commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target
> +	</location>
what is this addition for ?

2024-01-03 13:37 UTC, hengsin commented
2 other files that needs update:
- org.idempiere.p2.targetplatform.mirror.feature/feature.xml
- org.idempiere.p2.targetplatform/org.idempiere.p2.repository.target

2024-01-04 03:32 UTC, hieplq commented
thanks @hengsin for review. just commit fix for it

2024-01-04 12:14 UTC, hengsin requested changes

2024-01-04 12:14 UTC, hengsin commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target
>  version:               ${version_cleanup;${mvnVersion}}
please change sequenceNumber of target file (just increment it by 1 is fine).

2024-01-05 12:29 UTC, hengsin approved these changes
tested

2024-01-05 12:29 UTC, merged