IDEMPIERE-6016:test case to simulate transaction timeouts and ensure no open connections remain afterwards
idempiere/idempiere pull request #2219
Opened 2024-01-30 06:52 UTC by hieplq

To observe the connection leak, please revert commit 6acc6f31 before running this test case.

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [ ] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2024-01-30 07:06 UTC, hengsin commented on org.idempiere.test/src/org/idempiere/test/base/DBTest.java
> +
this needs to be executed in isolation from other test. to ensure that, add `@Isolated` and `@Execution(ExecutionMode.SAME_THREAD)` annotation to the DBTest class.

2024-01-31 11:06 UTC, hengsin commented
[pr2219.patch.txt](https://github.com/idempiere/idempiere/files/14110798/pr2219.patch.txt)
- replace abort with rollback
- use shorter duration for timeout test 2
- add Isolatead and same thread execution class annotation

2024-01-31 11:07 UTC, hengsin requested changes
hi @hieplq , please review attached patch, thanks.

2024-02-05 06:19 UTC, hieplq commented
>     * replace abort with rollback

Modifying this code, will the timeout now fire the AfterRollbackEvent instead of its original behavior?

2024-02-05 06:47 UTC, hengsin commented
> > ```
> > * replace abort with rollback
> > ```
> 
> Modifying this code, will the timeout now fire the AfterRollbackEvent instead of its original behavior?

No, to fire AfterRollbackEvent, you need to call Trx.rollback instead of Connection.rollback.

2024-02-05 07:45 UTC, hieplq commented
we need to call setAutoCommit (true) also?

2024-02-05 08:10 UTC, hengsin commented
> we need to call setAutoCommit (true) also?

You means to duplicate what's in Trx.close ? Well, perhaps it is safer to do that as well. I guess we can try to just call the rollback and close method of Trx instead.

2024-02-05 09:45 UTC, hieplq commented
> You means to duplicate what's in Trx.close ? 

yeb

> Well, perhaps it is safer to do that as well. I guess we can try to just call the rollback and close method of Trx instead.

This triggers the event, so timeouts case might require overloaded rollback/close methods to no raise event

2024-02-05 10:16 UTC, hengsin commented
hi @hieplq, I don't think any triggering of trx event (rollback, close) is a problem here.  Also, this is suppose to happens rarely and don't think we should put too much design effect into this.

2024-02-06 03:08 UTC, hengsin commented
hi @hieplq , I try with simplifying that to use existing trx.rollback and trx.close method and it seems work just fine.

[pr2219.patch1.txt](https://github.com/idempiere/idempiere/files/14174190/pr2219.patch1.txt)

2024-02-06 07:56 UTC, hieplq commented
it's ok for me

2024-02-06 12:05 UTC, hengsin approved these changes
tested

2024-02-06 12:05 UTC, merged