IDEMPIERE-6147: Add IsHtml on AD_Field and AD_UserDef_Field
idempiere/idempiere pull request #2366
Opened 2024-05-17 14:57 UTC by nmicoud

https://idempiere.atlassian.net/browse/IDEMPIERE-6147

# Pull Request Checklist

- [X] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [X] My code follows the best practices of this project
- [X] I have performed a self-review of my own code
- [X] My code is easy to understand and review. 
- [X] I have checked my code and corrected any misspellings
- [X] In hard-to-understand areas, I have commented my code.
- [X] My changes generate no new warnings
### Tests
- [X] I have tested the direct scenario that my code is solving
- [X] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2024-05-17 17:34 UTC, CarlosRuiz-globalqss requested changes

2024-05-17 17:34 UTC, CarlosRuiz-globalqss commented on migration/iD12/oracle/202405171607_IDEMPIERE-6147.sql
> +CREATE OR REPLACE VIEW AD_Field_vt(AD_Language, AD_Window_ID, AD_Tab_ID, AD_Field_ID, AD_Table_ID, AD_Column_ID, Name, Description, Help, IsDisplayed, DisplayLogic, DisplayLength, SeqNo, SortNo, IsSa
lines > 2499 characters are not valid in oracle sqlplus - this line needs to be split, and same for ad_field_v

2024-05-17 17:34 UTC, CarlosRuiz-globalqss commented on org.adempiere.base/src/org/compiere/model/I_AD_Field.java
> +    /** Column name AD_Field_ID */
is it possible that you are using a slightly different version of the core ModelGenerator classes?

why the order of the fields are different when you run it?

or is maybe the collation setting on your postgres?

2024-05-17 17:46 UTC, CarlosRuiz-globalqss commented on org.adempiere.base/src/org/compiere/model/I_AD_Field.java
> +    /** Column name AD_Field_ID */
@nmicoud - what is the result of running the following query in your database?
```sql
SELECT 'AD_Field_UU' UNION
SELECT 'AD_Field_ID' UNION 
SELECT 'AD_Column_ID' UNION
SELECT 'AD_FieldGroup_ID'
ORDER BY 1
```

in my database the fields are ordered this way:
AD_Column_ID
AD_FieldGroup_ID
AD_Field_ID
AD_Field_UU

2024-05-17 18:20 UTC, CarlosRuiz-globalqss commented on org.adempiere.base/src/org/compiere/model/I_AD_Field.java
> +    /** Column name AD_Field_ID */
nevermind - I found the issue and opened ticket and pull request:
https://idempiere.atlassian.net/browse/IDEMPIERE-6149

2024-05-20 05:12 UTC, nmicoud commented
BTW, there was a not commited change (moving scripts to iD11), as I think it can be integrated in stable version directly?

2024-05-20 17:49 UTC, nmicoud commented
> > BTW, there was a not commited change (moving scripts to iD11), as I think it can be integrated in stable version directly?
> 
> Hi @nmicoud - better to keep it in iD12, it will be difficult to integrate because it conflicts with IDEMPIERE-3989

Done !

2024-05-20 18:39 UTC, CarlosRuiz-globalqss commented
Thanks @nmicoud - sorry to bother you, can you please generate again the model classes after applying the fix for IDEMPIERE-6149 ?

2024-05-21 06:02 UTC, nmicoud commented
> Thanks @nmicoud - sorry to bother you, can you please generate again the model classes after applying the fix for IDEMPIERE-6149 ?

Hi @CarlosRuiz-globalqss : done

2024-05-21 16:10 UTC, CarlosRuiz-globalqss approved these changes

2024-05-21 16:10 UTC, merged