IDEMPIERE-6152 - Adjustment for the use of aliases in the MLookupFact…
idempiere/idempiere pull request #2373
Opened 2024-05-20 16:58 UTC by VitorVilla

…ory class.

# Pull Request Checklist

- [ ] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [ ] My code follows the best practices of this project
- [ ] I have performed a self-review of my own code
- [ ] My code is easy to understand and review. 
- [ ] I have checked my code and corrected any misspellings
- [ ] In hard-to-understand areas, I have commented my code.
- [ ] My changes generate no new warnings
### Tests
- [ ] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2024-05-21 06:26 UTC, hengsin commented on org.adempiere.base/src/org/compiere/model/MLookupFactory.java
> +
please remove all the white space only changes above.

2024-05-22 10:10 UTC, CarlosRuiz-globalqss requested changes

2024-05-22 10:10 UTC, CarlosRuiz-globalqss commented on org.adempiere.base/src/org/compiere/model/MLookupFactory.java
> +		embedSQL.append(" FROM ").append(TableName).append(" alias");
Please check comment at:
https://idempiere.atlassian.net/browse/IDEMPIERE-6152?focusedCommentId=50872

Also, it's possible that "alias" is a [reserved word in some databases](https://www.drupal.org/docs/develop/coding-standards/list-of-sql-reserved-words), better to use a different name

2024-05-22 10:14 UTC, CarlosRuiz-globalqss commented
@VitorVilla - four things about pull requests:

1 - we usually write the commit message with similar wording as the JIRA ticket - in this case I edited the subject of the pull request to make it more accurate

2 - as a second line of the commit message we usually add more explanation about the solution on the commit.  I added your original message on the pull request as part of the description

3 - we add a link to the ticket to ease navigation from peer reviewers

4 - you must fill the boxes of what you did on the "Pull Request Checklist"

2024-05-24 02:13 UTC, hengsin commented on org.adempiere.base/src/org/compiere/model/MLookupFactory.java
> +
Your new commit doesn't fix this. If you are using Eclipse, Turn off "Ignore white space" in Preferences > General > Compare/Patch.

2024-05-24 02:15 UTC, hengsin commented on org.adempiere.base/src/org/compiere/model/MLookupFactory.java
> +
Also, if you have install the any edit plugin, turn off "Remove trailing whitespace" in Preferences > General > Editors > AnyEdit Tools

2024-07-05 16:55 UTC, closed without merging

2024-07-05 17:46 UTC, VitorVilla commented
https://github.com/idempiere/idempiere/pull/2414 
New PR Opened, close in this to keep this discussion in history