IDEMPIERE-6161:JasperReports encounters issues using encrypted functions due to incompatible dependencies
idempiere/idempiere pull request #2381
Opened 2024-05-27 05:54 UTC by hieplq

[IDEMPIERE-6161](https://idempiere.atlassian.net/browse/IDEMPIERE-6161)

**NOTE**: why don't update to 1.78.1?
The target platform encountered a resolution issue (Tycho was still able to build successfully)

The resolution issue can be addressed by disregarding the `includeDependencyScope='compile'` directive and including bcprov-jdk18on, bcutil-jdk18on, and bcpkix-jdk18on dependencies separately

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2024-05-31 08:29 UTC, hengsin commented
need to change the sequence of the target platform.

2024-06-03 09:34 UTC, hengsin commented on org.idempiere.p2.targetplatform/org.idempiere.p2.targetplatform.target
> +      <version>1.77</version>
please update the version in `maven.locations.xml` as well.

2024-06-03 09:35 UTC, hengsin commented on org.idempiere.test/src/org/idempiere/test/jasper/HandleSetupConfigurationPdfExport.java
> +package org.idempiere.test.jasper;
please add license header

2024-06-03 11:11 UTC, CarlosRuiz-globalqss commented
Confirmed the test case fails before and passes after the change.

2024-06-03 11:32 UTC, hengsin commented on org.idempiere.test/src/org/idempiere/test/jasper/HandleSetupConfigurationPdfExport.java
> +	public final static String JP_KEY_PROCESS_INFO = "PROCESS_INFO";
should use constant from `JREventManage` instead.

2024-06-06 02:55 UTC, hengsin requested changes
please address inline comments, thanks.

2024-06-06 12:48 UTC, hengsin approved these changes
looks good and tested by Carlos

2024-06-06 12:48 UTC, merged