IDEMPIERE-6265 Voiding a invoice does not update invoice tax.
idempiere/idempiere pull request #2493
Opened 2024-10-17 14:13 UTC by VitorHenri

# Pull Request Checklist

- [X] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [X] My code follows the best practices of this project
- [X] I have performed a self-review of my own code
- [X] My code is easy to understand and review. 
- [X] I have checked my code and corrected any misspellings
- [X] In hard-to-understand areas, I have commented my code.
- [X] My changes generate no new warnings
### Tests
- [X] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2024-10-17 16:11 UTC, ocurieles requested changes
Hi, i Think is not good put the invoice in zero, and don't use a save().. use saveEx().

 I don't know why you need calculateTaxFromLines here

2024-10-18 05:19 UTC, hengsin commented on org.adempiere.base/src/org/compiere/model/MInvoice.java
> +		}
Should just clear all invoice tax records instead of recalculate here (there's nothing to re-calculate here).

2024-10-25 14:52 UTC, VitorHenri commented
I adjusted it to just delete the tax records from the invoice, as for save and saveEx I believe it will not be necessary, when run through the window the MWFActivity will take care of saving the po.

2024-10-26 11:44 UTC, hengsin commented
please see comments at ticket, thanks.

2024-10-30 02:05 UTC, hengsin commented
hi @VitorHenri , we would have to close this pull request if you can't provide a re-produceable test case.

2024-10-30 14:14 UTC, VitorHenri commented
Hi @hengsin, sorry for the delay, after analyzing it further, the treatment must be done in my own ITaxProvider implementation, Idempiere's StardardTaxProvider already recalculates the invoice taxes, resetting them to zero in case of voiding the document. Sorry for the mistake, I'll close the PR.

2024-10-30 14:14 UTC, closed without merging