IDEMPIERE-6306 : Improve Calendar UI
idempiere/idempiere pull request #2553
Opened 2024-11-21 00:38 UTC by uthadehikaru

https://idempiere.atlassian.net/browse/IDEMPIERE-6306

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [x] In hard-to-understand areas, I have commented my code.
- [x] My changes generate no new warnings
### Tests
- [x] I have tested the direct scenario that my code is solving
- [x] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2024-11-21 01:31 UTC, hengsin requested changes
as usual, after making changes to css, you need to update lang-addon.xml

2024-11-21 01:31 UTC, hengsin commented on org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/zul/calendar/calendar.css
> +	/* border-top: 4px solid #FFFFFF; */
remove, don't remark.

2024-11-21 06:55 UTC, hengsin commented
hi @uthadehikaru , the following patch make clicking on the day number trigger create ticket event:
[dpcalendar.patch.txt](https://github.com/user-attachments/files/17841093/dpcalendar.patch.txt)

please merge it if tested ok.

2024-11-24 04:57 UTC, uthadehikaru commented
> hi @uthadehikaru , the following patch make clicking on the day number trigger create ticket event: [dpcalendar.patch.txt](https://github.com/user-attachments/files/17841093/dpcalendar.patch.txt)
> 
> please merge it if tested ok.

tested ok and I also implement on calendar window

2024-11-24 05:09 UTC, hengsin approved these changes
tested

2024-11-24 05:10 UTC, merged