IDEMPIERE-6266 Drop attachment broken on release-12
idempiere/idempiere pull request #2555
Opened 2024-11-22 16:43 UTC by CarlosRuiz-globalqss

https://idempiere.atlassian.net/browse/IDEMPIERE-6266

# Pull Request Checklist

- [ ] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [ ] My code follows the best practices of this project
- [ ] I have performed a self-review of my own code
- [ ] My code is easy to understand and review. 
- [ ] I have checked my code and corrected any misspellings
- [ ] In hard-to-understand areas, I have commented my code.
- [ ] My changes generate no new warnings
### Tests
- [ ] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2024-11-24 12:49 UTC, CarlosRuiz-globalqss commented
Hi @hengsin - I tested this and I find it functionally correct, it restores the ability to upload attachments using drag and drop, it extended the area of drop to the whole dialog, and it preserves the presentation of the drop area as surrounded by a green dotted line.

The only thing that is removed is an upload progress bar that was shown on drag & drop action, but not when using the button.

IMO that's not a big deal an as this is an important fix for a broken feature I would suggest to move it ahead.

I just did functional test, can you please check it code-wise?

2024-11-24 14:13 UTC, hengsin requested changes

2024-11-24 14:13 UTC, hengsin commented on org.idempiere.zk.iceblue_c.theme/src/web/theme/iceblue_c/css/theme.css.dsp
> +
you need to change lang-addon.xml after changes to theme css

2024-11-24 14:13 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/web/js/org/idempiere/commons/input.js
> +	});
To avoid potential conflict with future zk update, probably safer to use custom prefix (for e.g `_id_`) for all custom property and function.

2024-11-24 14:13 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/web/js/org/idempiere/commons/input.js
> +				wgUploadBt = zk.Widget.$(this.uploadID);
should use `let` for local variable. also, perhaps better to use a more obvious property name like `uploadButtonId`

2024-11-25 01:46 UTC, hengsin approved these changes
looks good

2024-11-25 01:51 UTC, hengsin approved these changes

2024-11-25 01:52 UTC, hengsin commented
hi @CarlosRuiz-globalqss , the change looks good but I'm not github complain there's a conflict with master branch that needs to be resolved.

2024-11-25 04:13 UTC, hengsin commented
hi @CarlosRuiz-globalqss and @hieplq , I try to test today with firefox but it doesn't seems to works for me. Can your re-test to confirm ?

2024-11-25 08:35 UTC, hengsin approved these changes

2024-11-25 08:41 UTC, hengsin requested changes

2024-11-25 08:41 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/web/js/org/idempiere/commons/input.js
> +				wgUploadBt = zk.Widget.$(this._id_uploadButtonId);
should use `let`, i.e `let wgUploadBt = zk.Widget.$(this._id_uploadButtonId);`

2024-11-26 12:54 UTC, CarlosRuiz-globalqss commented
Hi @hieplq - because of IDEMPIERE-6314 this pull request has now conflicts.

The idea is that the box must not be droppable if the attachment is read-only, I tried to fix the conflicts, but for some reason the upload is not working for me anymore   :-(

2024-11-26 18:00 UTC, closed without merging