IDEMPIERE-6335 - Create parameter to specify document type in material receipt
idempiere/idempiere pull request #2581
Opened 2024-12-04 13:16 UTC by VitorVilla

https://idempiere.atlassian.net/browse/IDEMPIERE-6335

# Pull Request Checklist

- [x] My code follows the [code guidelines](https://wiki.idempiere.org/en/Contributing_to_Trunk) of this project
- [x] My code follows the best practices of this project
- [x] I have performed a self-review of my own code
- [x] My code is easy to understand and review. 
- [x] I have checked my code and corrected any misspellings
- [ ] In hard-to-understand areas, I have commented my code.
- [ ] My changes generate no new warnings
### Tests
- [ ] I have tested the direct scenario that my code is solving
- [ ] I checked all collaterals that can be affected by my changes, and tested other potential affected scenarios
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have added unit tests that prove my fix is effective or that my feature works
### Documentation
- [ ] I have made corresponding changes to the documentation as follows:
- - [ ] New feature (non-breaking change which adds functionality): I have created the New Feature page in the project wiki explaining the functionality and how to use it. If relevant, I have committed sample data to the core seed to have usable examples in GardenWorld.
- - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected): I have documented the change in a clear way that everyone in the community can understand the impact of the change.
- - [ ] Improvement (improves and existing functionality): This documentation is needed if the improvement changes the way the user interacts with the system or the outcome of a process/task changes. If it is just, for instance, a performance improvement, documentation might not be needed. 
- [ ] The changed/added documentation is in the project wiki (not privately-hosted pdf files or links pointing to a company website) and is complete and self-explanatory.

2024-12-04 13:17 UTC, VitorVilla commented
"Could you bring this to version 11?"

2024-12-10 14:15 UTC, VitorVilla commented on migration/iD11/oracle/202412041007_IDEMPIERE-6335.sql
> +INSERT INTO AD_Process_Para (AD_Process_Para_ID,AD_Client_ID,AD_Org_ID,IsActive,Created,CreatedBy,Updated,UpdatedBy,Name,Description,Help,AD_Process_ID,SeqNo,AD_Reference_ID,IsRange,AD_Val_Rule_ID,Fi
I adjusted it to use the centralizer

2024-12-11 17:39 UTC, CarlosRuiz-globalqss requested changes
can you please apply the following patch
[pr2581PR0.patch.txt](https://github.com/user-attachments/files/18099949/pr2581PR0.patch.txt)

I tested this successfully, so, is just needing that to approve it.

2024-12-11 18:40 UTC, VitorVilla commented
patch applied

2024-12-11 21:45 UTC, CarlosRuiz-globalqss approved these changes
tested

2024-12-11 21:45 UTC, merged