IDEMPIERE-4581 Model generator should isn't dialog it should be window
idempiere/idempiere pull request #434
Opened 2020-12-04 05:14 UTC by hieplq

use shutdown asyn to shutdown framework when close Model generator window

one unhappy thing remain:
when use -console then framework is shutdown but jdk still hang because "pipe-gosh --login --noshutdown" still live (for https://bugs.eclipse.org/bugs/show_bug.cgi?id=362412)
work-around: use -console 1234
by that way we can't access osgi command from console but can use "telnet localhost 1234" to use osgi command

2020-12-04 17:22 UTC, CarlosRuiz-globalqss requested changes
Hi @hieplq - I tested this:

- the positive effect is that the window is now seen by the operating system and I can switch to that window with Alt-Tab

- the negative effect is that the program doesn't end when I click on Cancel or close the window (note that the swing client can be closed, so maybe there is a mechanism there)

2020-12-05 11:50 UTC, hieplq commented
you need to wait for while for thread of timer at PackInApplicationActivator finish

on practice it isn't issue because time for user input to window will cover it

actual i see it's issue when packin folder run by model generator it should run only by main product (server application)

anyway can use replace 
Timer t = new Timer();
by
Timer t = new Timer(true);
to switch timer to deamon process to don't block exit jdk

2020-12-05 15:51 UTC, CarlosRuiz-globalqss commented
Hi @hieplq - I tested disabling pipo from the launcher and it worked fine.

Can you please check the attached patch (and integrate if you find it OK):
[launcher.txt](https://github.com/idempiere/idempiere/files/5647315/launcher.txt)

I disabled a lot of plugins from the launcher and still is running perfect.

Regards,

Carlos Ruiz

2020-12-05 16:21 UTC, CarlosRuiz-globalqss commented
Also, if you want to consider it - a minor improvement on the layout of the window:
[ModelGeneratorGBC.txt](https://github.com/idempiere/idempiere/files/5647378/ModelGeneratorGBC.txt)

2020-12-12 11:32 UTC, CarlosRuiz-globalqss commented
replaced with https://github.com/idempiere/idempiere/pull/463

2020-12-12 11:32 UTC, closed without merging