IDEMPIERE-4607 Cannot export windows via 2pack if any field has a Fie…
idempiere/idempiere pull request #483
Opened 2020-12-22 18:34 UTC by d-ruiz

…ld Group

https://idempiere.atlassian.net/browse/IDEMPIERE-4607

2020-12-22 19:26 UTC, CarlosRuiz-globalqss requested changes
See comments in ticket

2020-12-24 23:39 UTC, hengsin commented on org.adempiere.base/src/org/compiere/util/DisplayType.java
> +				return service.isDate(displayType);
typo

2020-12-26 13:35 UTC, d-ruiz commented on org.adempiere.base/src/org/compiere/util/DisplayType.java
> +				return service.isDate(displayType);
Fixed

2020-12-26 13:43 UTC, CarlosRuiz-globalqss commented on org.adempiere.base/src/org/adempiere/base/IDisplayTypeFactory.java
> +	public boolean isList (int displayType);
This change breaks the plugins that use the interface.

I suggest the following change for better backward compatibility:
[default_interface.txt](https://github.com/idempiere/idempiere/files/5743146/default_interface.txt)

2020-12-26 15:35 UTC, CarlosRuiz-globalqss approved these changes

2020-12-26 15:35 UTC, merged