IDEMPIERE-4611 Replace dependency to sun.security.tools.keytool with …
idempiere/idempiere pull request #486
Opened 2020-12-26 03:22 UTC by hengsin

https://idempiere.atlassian.net/browse/IDEMPIERE-4611

2020-12-26 15:49 UTC, CarlosRuiz-globalqss commented
Would be good to inactivate the menu entry (AD_Menu_ID=594) and the window (AD_Window_ID=389)

2020-12-26 16:22 UTC, CarlosRuiz-globalqss requested changes
Hi @hengsin - the test failed running the install.app or the install.console.app (or in server setup/setup-console)

The certificate is generated OK if I leave the State field empty, but when I fill the State with any value then the following exception is thrown:
```
17:21:41.037===========> KeyStoreMgt.createCertificate: certificate [37]
java.lang.RuntimeException: java.lang.IllegalArgumentException: Unknown object id - S - passed to distinguished name
	at org.compiere.install.KeyStoreMgt.selfcert(KeyStoreMgt.java:428)
	at org.compiere.install.KeyStoreMgt.createCertificate(KeyStoreMgt.java:255)
	at org.compiere.install.KeyStoreMgt.verify(KeyStoreMgt.java:116)
	at org.compiere.install.ConfigurationData.testAdempiere(ConfigurationData.java:476)
	at org.compiere.install.ConfigurationData.test(ConfigurationData.java:393)
	at org.compiere.install.ConfigurationPanel.test(ConfigurationPanel.java:575)
	at org.compiere.install.ConfigurationPanel$1.construct(ConfigurationPanel.java:528)
	at org.compiere.install.util.SwingWorker$2.run(SwingWorker.java:68)
	at java.base/java.lang.Thread.run(Thread.java:834)
caused by: java.lang.IllegalArgumentException: Unknown object id - S - passed to distinguished name
	at org.bouncycastle.asn1.x500.style.IETFUtils.decodeAttrName(Unknown Source)
	at org.bouncycastle.asn1.x500.style.BCStyle.attrNameToOID(Unknown Source)
	at org.bouncycastle.asn1.x500.style.IETFUtils.rDNsFromString(Unknown Source)
	at org.bouncycastle.asn1.x500.style.BCStyle.fromString(Unknown Source)
	at org.bouncycastle.asn1.x500.X500Name.<init>(Unknown Source)
	at org.bouncycastle.asn1.x500.X500Name.<init>(Unknown Source)
	at org.compiere.install.KeyStoreMgt.createCertificate(KeyStoreMgt.java:443)
	at org.compiere.install.KeyStoreMgt.selfcert(KeyStoreMgt.java:414)
	at org.compiere.install.KeyStoreMgt.createCertificate(KeyStoreMgt.java:255)
	at org.compiere.install.KeyStoreMgt.verify(KeyStoreMgt.java:116)
	at org.compiere.install.ConfigurationData.testAdempiere(ConfigurationData.java:476)
	at org.compiere.install.ConfigurationData.test(ConfigurationData.java:393)
	at org.compiere.install.ConfigurationPanel.test(ConfigurationPanel.java:575)
	at org.compiere.install.ConfigurationPanel$1.construct(ConfigurationPanel.java:528)
	at org.compiere.install.util.SwingWorker$2.run(SwingWorker.java:68)
```

2020-12-27 14:07 UTC, CarlosRuiz-globalqss approved these changes

2020-12-27 14:07 UTC, merged

2020-12-27 14:56 UTC, hieplq commented
--add-exports on pom.xml also should remove