IDEMPIERE-4622  Cross Tenant UserDefInfo, Role
idempiere/idempiere pull request #503
Opened 2020-12-31 12:48 UTC by igorpojzl

https://idempiere.atlassian.net/browse/IDEMPIERE-4622

2021-01-01 18:05 UTC, CarlosRuiz-globalqss requested changes

2021-01-01 18:05 UTC, CarlosRuiz-globalqss commented on org.adempiere.base/src/org/compiere/model/MUserDefInfo.java
> +			m_fullList = new Query(ctx, MUserDefInfo.Table_Name, "IsActive='Y'", null).setClient_ID().list();
This is wrong, as is designed m_fullList is intended to have a list from all tenants.

To make this work would require a refactor similar to what @hengsin did in MUserDefWin here:
https://github.com/idempiere/idempiere/commit/2ab2211f81f4ecb3928a56506ddd7712731a1036#diff-18f1e200c9da97cb1ba9cb7290831a270c9dd9d5a9721ff68628a16dd1b574fd

2021-01-01 18:05 UTC, CarlosRuiz-globalqss commented on org.adempiere.base/src/org/compiere/model/MUserDefProc.java
> +			m_fullList = new Query(ctx, MUserDefProc.Table_Name, "IsActive='Y'", null).setClient_ID().list();
Same as comment above for MUserDefProc

2021-01-01 18:05 UTC, CarlosRuiz-globalqss commented on org.adempiere.base/src/org/compiere/model/MUserRoles.java
> +		.setClient_ID()
This seems wrong, filtering by AD_Client_ID this way will exclude the roles the user can have in System tenant.

I think the filter must be something like adding in the whereClause
`AND AD_Client_ID IN (0,?)`
and adding the clientID to the parameters

2021-01-01 22:56 UTC, hengsin commented
For MUserDefInfo.m_fullList, please refer to the same changes that I've made for MUserDefWin (replace by m_fullMap).

2021-01-05 15:12 UTC, igorpojzl commented
Commited all Requests.

2021-01-06 11:43 UTC, norbertbede commented
@CarlosRuiz-globalqss @hengsin  , can you please help you sort out, if any investigation needed, we are available. asap.

2021-01-06 12:17 UTC, CarlosRuiz-globalqss commented on org.adempiere.base/src/org/compiere/model/MUserDefProc.java
> +			m_fullList = new Query(ctx, MUserDefProc.Table_Name, "IsActive='Y' AND AD_Client_ID IN (0,?)", null).setParameters(Env.getAD_Client_ID(ctx)).list();
Hi @igorpojzl 

You must apply here the same approach using m_fullMap as in MUserDefInfo

Regards,

Carlos Ruiz

2021-01-07 07:48 UTC, igorpojzl commented
Commited Changes.

2021-01-07 10:27 UTC, CarlosRuiz-globalqss approved these changes
Tested successfully

2021-01-07 10:27 UTC, merged