IDEMPIERE-4657 Search Dialog Columns are duplicated when table is present in multiple window tabs.
idempiere/idempiere pull request #540
Opened 2021-01-20 15:24 UTC by CarlosRuiz-globalqss

https://idempiere.atlassian.net/browse/IDEMPIERE-4657

2021-01-20 17:25 UTC, Soundbytes requested changes

2021-01-20 18:07 UTC, Soundbytes commented
here is a query that works for me:

```
SELECT c.ColumnName, c.AD_Reference_ID, c.IsKey, f.IsDisplayed, 
c.AD_Reference_Value_ID, c.ColumnSql, c.AD_Column_ID
FROM (SELECT t.AD_Window_ID, tab.AD_Tab_ID from AD_Table t 
 INNER JOIN AD_Tab tab ON (t.AD_Window_ID=tab.AD_Window_ID) 
 WHERE t.AD_Table_ID=? 
 ORDER BY tab.SeqNo FETCH FIRST ROW ONLY) tt
 INNER JOIN AD_Field f ON (tt.AD_Tab_ID=f.AD_Tab_ID)
 JOIN AD_Column c on f.AD_Column_ID=c.AD_Column_ID
WHERE 
 (c.IsKey='Y' OR 
 (f.IsEncrypted='N' AND f.ObscureType IS NULL)) 
ORDER BY c.IsKey DESC, f.SeqNo;
```

It will produce only the records corresponding to the first tab.
(Disclaimer: Tested only with postgresql)

2021-01-21 11:09 UTC, CarlosRuiz-globalqss commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/panel/InfoGeneralPanel.java
> +		sql = "SELECT DISTINCT c.ColumnName, c.AD_Reference_ID, c.IsKey, f.IsDisplayed, c.AD_Reference_Value_ID, c.ColumnSql, c.AD_Column_ID, f.SeqNo "
Thanks, made a new commit with a better query.

2021-01-21 16:20 UTC, Soundbytes approved these changes
Works as expected. (Of course I like my own proposal better but they both produce the same result))

2021-01-21 16:27 UTC, merged