IDEMPIERE-4681 Can't use hidden column in display logic
idempiere/idempiere pull request #561
Opened 2021-01-29 08:25 UTC by hengsin

https://idempiere.atlassian.net/browse/IDEMPIERE-4681

2021-01-30 09:39 UTC, CarlosRuiz-globalqss requested changes
comment on ticket

2021-02-06 13:27 UTC, CarlosRuiz-globalqss commented
Hi @hengsin,

About
> test case failed:
> Display Logic = @SO_CreditAvailable:0@=0

changing
`x.DisplayLogic Like '%@'||c.ColumnName||'@%'`
with
`x.DisplayLogic Like '%@'||c.ColumnName||'%'`
can do the trick.

But I'm not sure the consequences of getting extra columns that are unrelated, with this fix you could also get wrongly a column named @SO_CreditAvailable_New@ - does it have consequences getting an unrelated column?

If yes, then maybe an OR could be better - but that makes it dependent on more things that could be implemented in the display logic, like @C_BPartner_ID.Name@ or @DateAcct<yyyy-mm-dd>@

WDYT?

Regards,

Carlos Ruiz

2021-02-07 13:19 UTC, hengsin commented
Hi @CarlosRuiz-globalqss ,

I think it is safer to use the OR approach.

Regards,
Low

2021-02-16 10:14 UTC, CarlosRuiz-globalqss approved these changes

2021-02-16 10:14 UTC, merged