IDEMPIERE-4702 Messagebox enhancement: Esc key closes Dialog with cancel
idempiere/idempiere pull request #586
Opened 2021-02-14 18:36 UTC by Soundbytes

This replaces the closed PR of the same name.

2021-02-15 11:55 UTC, CarlosRuiz-globalqss commented
This test passes successfully:

- navigate to _Invoice (Customer)_ 200002 in GardenWorld
- click on _Posted_ button to open the _Posting_ window
- click on the _Re-Post_ button
- now this dialog can be closed with _Esc_ keystroke assuming the _Cancel_ button was pushed


Question for @hengsin - are you OK with the annotations approach?  Or is there a better way to implement it?

Regards,

Carlos Ruiz

2021-02-15 13:28 UTC, hengsin requested changes

2021-02-15 13:28 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/component/Messagebox.java
> +	@Listen("onCancel = #form")
Should be just @Listen("onCancel") here, MessageBox doesn't has an element with id="form".

2021-02-16 00:40 UTC, hengsin approved these changes
tested

2021-02-16 00:41 UTC, merged