IDEMPIERE-4696 Wrong GL Currency Balancing in payment allocation for payment reverse/accrual
idempiere/idempiere pull request #621
Opened 2021-03-10 02:26 UTC by etantg

https://idempiere.atlassian.net/browse/IDEMPIERE-4696

Payment document Jan-21 with EUR 1000. Rate = 1:30
Reverse/Accrual in Feb-21. Rate = 1:31
WRONG GL posting:
DR Unallocated Cash 30000
CR Unallocated Cash        31000
DR Currency Balancing 1000

Correct posting would be: 
DR Unallocated Cash 30000
CR Unallocated Cash        31000
DR Realized Loss 1000

2021-03-11 09:38 UTC, hengsin commented on org.idempiere.test/src/org/idempiere/test/base/AllocationTest.java
> +public class AllocationTest extends AbstractTestCase {
There's another class with the same name at org.idempiere.test.model package. It will be less confusing to merge the two instead.

2021-03-11 09:38 UTC, hengsin commented on org.idempiere.test/src/org/idempiere/test/base/AllocationTest.java
> +	public void testPaymentReversePosting() {
To complete the picture, please add a similar test for posting without reversal.

2021-03-11 09:40 UTC, hengsin requested changes
please address the changes requested.

2021-03-12 11:22 UTC, etantg commented on org.idempiere.test/src/org/idempiere/test/base/AllocationTest.java
> +public class AllocationTest extends AbstractTestCase {
- Merged the unit test to org.idempiere.test.model.AllocationTest class
- Deleted org.idempiere.test.base.AllocationTest class

2021-03-12 11:23 UTC, etantg commented on org.idempiere.test/src/org/idempiere/test/base/AllocationTest.java
> +	public void testPaymentReversePosting() {
Added another unit test: AllocationTest.testAllocatePaymentPosting

2021-03-15 09:52 UTC, hengsin requested changes
unit test fail with 2 error:

org.opentest4j.AssertionFailedError: -31000.0!=30000 ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:193)
	at org.idempiere.test.model.AllocationTest.testAllocatePaymentPosting(AllocationTest.java:518)

and 

org.opentest4j.AssertionFailedError: -31000.0!=30000 ==> expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:193)
	at org.idempiere.test.model.AllocationTest.testPaymentReversePosting(AllocationTest.java:416)

2021-03-15 10:58 UTC, etantg commented
Fixed the unit tests

2021-03-15 13:17 UTC, hengsin approved these changes
unit test pass. manual test pass by Michael Powacht

2021-03-15 13:18 UTC, merged