IDEMPIERE-4839 IQuickEdit interface
idempiere/idempiere pull request #731
Opened 2021-06-18 11:44 UTC by Soundbytes

Jira Ticket: https://idempiere.atlassian.net/browse/IDEMPIERE-4839

2021-06-18 13:47 UTC, hengsin requested changes
First, there should be javadoc for the methods at IQuickForm interface. Second, this seems incomplete as the onQuickForm() method at AbstractADWindowContent is not touch at all.

2021-06-18 15:10 UTC, Soundbytes commented
> First, there should be javadoc for the methods at IQuickForm interface. 
Will be added.

> Second, this seems incomplete as the onQuickForm() method at AbstractADWindowContent is not touch at all.
Great Idea! The initial idea that I have implemented here was to make the quickform dialog available as a custom form. Since the form is opened via toolbar button or menu entry I did not have to touch the onQuickForm() method.
I'll be happy to extend the patch and provide an IQuickEdit osgi service as an alternative way to access the functionality. 
I'd however prefer to add that as a separate commit.

2021-06-20 03:59 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/WQuickForm.java
> +public class WQuickForm extends Window implements IQuickForm // EventListener <Event>, DataStatusListener
please remove the //... part

2021-06-20 04:00 UTC, hengsin commented on org.adempiere.ui.zk/WEB-INF/src/org/adempiere/webui/apps/form/IQuickForm.java
> +	public void dispose();
please add javadoc for all the methods

2021-06-20 04:01 UTC, hengsin requested changes
please address the requested changes.

2021-06-22 06:35 UTC, hengsin approved these changes
looks good.

2021-06-22 06:35 UTC, merged