IDEMPIERE-4899 Report: print product instance attribute name and valu…
idempiere/idempiere pull request #814
Opened 2021-08-04 05:59 UTC by hengsin

…e as column

https://idempiere.atlassian.net/browse/IDEMPIERE-4899

2021-08-04 11:55 UTC, CarlosRuiz-globalqss requested changes
tests failed
please check [comments in ticket](https://idempiere.atlassian.net/browse/IDEMPIERE-4899?focusedCommentId=47402)

2021-08-05 08:35 UTC, hengsin commented
> tests failed
> please check [comments in ticket](https://idempiere.atlassian.net/browse/IDEMPIERE-4899?focusedCommentId=47402)

I've fixed the issues reported except the font issue, can't reproduce that.

2021-08-05 16:32 UTC, CarlosRuiz-globalqss commented
[comments in ticket](https://idempiere.atlassian.net/browse/IDEMPIERE-4899?focusedCommentId=47415)

2021-08-06 09:11 UTC, CarlosRuiz-globalqss approved these changes

2021-08-06 09:12 UTC, merged