IDEMPIERE-4946 : Add IsShowInDashboard, SeqNo and ImageURL on AD_User…
idempiere/idempiere pull request #866
Opened 2021-09-06 13:30 UTC by nmicoud

…Def_Info

2021-09-07 07:47 UTC, nmicoud commented
Hi,
I just added a change to use the ImageURL from AD_UserDef_Info.
But seems the image is not shown on last version (at least on my local machine) but I can't find where is the issue.

2021-09-15 11:17 UTC, CarlosRuiz-globalqss requested changes

2021-09-15 11:17 UTC, CarlosRuiz-globalqss commented on migration/i8.2z/oracle/202109061500_IDEMPIERE-4946.sql
> +SELECT register_migration_script('202108271700_IDEMPIERE-49346.sql') FROM dual
The filename is wrong both in the postgresql and oracle scripts

2021-09-17 13:56 UTC, CarlosRuiz-globalqss approved these changes

2021-09-17 13:56 UTC, merged